api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        json: ['application/json']
        json_ld: ['application/ld+json']
    use_symfony_listeners: true
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
